# Generated by Django 3.0.5 on 2021-02-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Street', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=11, verbose_name='Volume Number')),
                ('Job_Title', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=150)),
                ('City_Town_Work', models.CharField(max_length=50)),
                ('Country_Work', models.CharField(max_length=50)),
                ('Start_Date_Work', models.CharField(max_length=16)),
                ('End_Date_Work', models.CharField(max_length=16)),
                ('School_Name', models.CharField(max_length=150)),
                ('City_Town_School', models.CharField(max_length=50)),
                ('Country_School', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=150)),
                ('Graduation_Date', models.CharField(max_length=16)),
                ('University_Name', models.CharField(max_length=255)),
                ('Skills_1', models.CharField(max_length=50)),
                ('Skills_2', models.CharField(max_length=50)),
                ('Skills_3', models.CharField(max_length=50)),
                ('Skills_4', models.CharField(max_length=50)),
                ('Skills_5', models.CharField(max_length=50)),
                ('Skills_6', models.CharField(max_length=50)),
                ('Skills_7', models.CharField(max_length=50)),
                ('Skills_8', models.CharField(max_length=50)),
                ('Skills_9', models.CharField(max_length=50)),
                ('pdf_cv', models.CharField(max_length=50)),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=150)),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostsJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Job_Title', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=350)),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
