# Generated by Django 3.0.5 on 2021-06-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_auto_20210318_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
